### ISSUE TITLE
Possible new color system

### ISSUE THREAD

**Issue by andrew-levy** [andrew-levy/swiftui-react-native#12]
## Currently there are a few ways to apply colors to views:

1. `UIColor` object. This is an object you can import that has `dark` and `light` properties. Inside those, there are each individual colors. 

2. `useUIColor` hook. this hook returns a dynamic form of the above UIColor object that decides between dark and light based on the current color scheme. 

3. You can also just pass in a hex value or any of the built in react native color values. 

## Proposed System:

Pass in the name of the swiftui color (as a string) that will map to the correct hex value. This will provide autocomplete and users won't need to use the hook or object.

example:
`backgroundColor=“systemBlue”`

where,
`type backgroundColor = keyof UIColor.light | string` or something like that. 

The logic would go something like this:
- if the string is a key of one of the uicolors, use the corresponding value
- else, just use that value as its probably a hex or rgba value.

In order to incorporate dark mode, we would have to use the `useColorScheme` hook internally within each component rather than having the user use it (I like this better - less work for the user). 

utils/colors
```typescript 
const getColor = (color: string, colorScheme: 'dark' | 'light') => {
  const palette = UIColor[colorScheme];
  if (palette[color]) return palette[color]
  return color
};
```

then in each component 
```jsx 
const colorScheme = useColorSheme();

…getColor(backgroundColor, colorScheme),
```

Open questions:
- Should we still include the old way to get colors?
- Does the autocompleting just work for TS or does it work for JS too? 
- Should we also do this with alignment, fonts, etc? yes i think

**Comment by andrew-levy** [comment]
@zpg6 Let me know what you think. I will probably start working on this soon.

**Comment by zpg6** [comment]
I like this a lot. Interested to see how it looks and feels when you go to use it
