### ISSUE TITLE
Proposing hot reload for development env

### ISSUE THREAD

**Issue by zpg6** [andrew-levy/swiftui-react-native#13]
(This is a "nice to have", just proposing at this time)

I have been thinking that putting the example in this repository and using something like `nodemon` would greatly improve my efficiency. 

### Here are my steps currently:

On `swiftui-react-native`:
```
yarn run clean-build
``` 

On `swiftui-react-native-example`
1. Quit metro (if running)
2. Restart metro with:
```
rm -rf node_modules && yarn install && yarn start --reset-cache
```
3. Wait for metro to load up, then hit `R`to reload simulator(s).

**Comment by andrew-levy** [comment]
This would be cool to see. Feel free to take a crack at it!

**Comment by andrew-levy** [comment]
Did you try anything like this yet within the example proj? I think this is exactly what you want. https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557

**Comment by zpg6** [comment]
> Did you try anything like this yet within the example proj? I think this is exactly what you want. https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557

I have not, will try this first before having to add any devDependecies.

**Comment by zpg6** [comment]
If I get something working, I think it'd be productive to work off the same example app. Maybe expand to allow us to try things outside of a List Section?

I've been on my own branch saving zero of my exploratory testing and I'm full of guilt about it hahaha

**Comment by zpg6** [comment]
> Did you try anything like this yet within the example proj? I think this is exactly what you want. https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557

https://stackoverflow.com/a/47403470/6074395 darn

**Comment by andrew-levy** [comment]
ah damn. if those alternative suggested don't work, another alternative could be this:

- add a new script in the package.json "build-example"
- it would call the clean-build script and then move the output dist folder into your example app project. 

`"build-example": "npm run clean-build && copfiles dist ../swiftui-react-native-example"`

or something like that (no clue if that is correct but the idea should work). That way all you would have to do is make a change, then run this script. But we would need to change the imports :/

**Comment by zpg6** [comment]
Pending your review to [my pull on the example repo](https://github.com/andrew-levy/swiftui-react-native-example/pull/1), I think this can be closed. (No action needed on this repo to resolve issue).
