### ISSUE TITLE
Chevron accessory of Link component

### ISSUE THREAD

**Issue by prinsss** [andrew-levy/swiftui-react-native#21]
I've been searching for iOS-style React Native component library for a while and this is just what I want. Thanks for the awesome project!

While using `Link` component in a List, I found that the chevron icon on the right side is missing. The screenshots in README shows a Link component with chevron icon, but it does not appear in my app nor the example app.

Is there any way to add this in the latest version of swiftui-react-native? Thanks!

P.S. I've tried something like this but it looks much different with the native `UITableViewCell.AccessoryType.disclosureIndicator`.

```jsx
<Button action={() => navigation.navigate('Drawing')}>
  <Text alignment="leading">Button</Text>
  <Image systemName="chevron.forward" />
</Button>
```

**Comment by andrew-levy** [comment]
Hey glad to hear you're liking it! Do you have the dependency `react-native-sfsymbols` installed correctly? This library uses it under the hood to display sf symbols like the chevron. If you think you have it installed correctly, I can take a look to see if so can reproduce the error. 

Just a heads up, @zpg6 and I are working on some new features for a v4 release with some better documentation and feature support. Should be out in the next month or so.

**Comment by zpg6** [comment]
> Just a heads up, @zpg6 and I are working on some new features for a v4 release with some better documentation and feature support. Should be out in the next month or so. 

@prinsss Stay tuned 🚀

**Comment by prinsss** [comment]
Thanks for the quick replies. Nice to hear that!

The dependencies are installed correctly since other SF Symbols are rendering well. I grabbed the source code of the example app from [here](https://github.com/andrew-levy/swiftui-react-native-example) and changed it a little bit:

```jsx
<List inset header="Buttons">
  <Button action={() => setShowAlert(true)}>
    <Text alignment="leading">Button</Text>
  </Button>
  <Link destination="https://www.apple.com">
    <Text alignment="leading">Link</Text>
  </Link>
  <Link
    destination="https://www.apple.com"
    style={{
      flexDirection: 'row',
    }}>
    <Text alignment="leading" style={{ flex: 1 }}>
      With SF Symbol
    </Text>
    <Image systemName="info.circle" />
    <Image systemName="chevron.forward" />
  </Link>
</List>
```

And here is the screenshot after running the example app:

<img width="503" alt="Snipaste_2022-03-06_06-18-47" src="https://user-images.githubusercontent.com/11206497/156901779-ef3b27fe-95a4-4bc9-ab20-2991be497c75.png">

**Comment by andrew-levy** [comment]
Ah okay I see. The way it's currently set up, Link and Button components don't "know" that they are in a list, so they don't automatically add the chevron. The only way to achieve this right now is with an Image component like you put manually. We wont always be able to replicate how it works in SwiftUI, but I can look to see if I can implement something like that.

**Comment by prinsss** [comment]
It would be nice if we could have an option to do that. Thank you!

**Comment by andrew-levy** [comment]
@prinsss Hey. So i just checked the default behavior in SwiftUI and it seems like SwiftUI does not automatically add a a chevron to `Link` when they shows up in a list. let me know if this address the issue you were having so we can close this issue out.

<img width="892" alt="Screen Shot 2022-03-06 at 9 10 01 AM" src="https://user-images.githubusercontent.com/29075740/156926859-81f5d11f-4714-4dd7-a2df-7fe807c3c587.png">

That being said, it does show up when you use `NavigationLink` inside of a list, which I plan to implement in a complementary library with all navigation views. Maybe `swiftui-react-native/navigation` ? TBD.

**Comment by prinsss** [comment]
Oh, yes, I meant `NavigationLink` which has a chevron. I used that for navigating to new content. Sorry for the confusion. 🙏

I've noticed that in the previous version (v1.9.4) of the library there was actually a component called [`NavigationLink`](https://github.com/andrew-levy/swiftui-react-native/blob/v1.9.4/src/views/NavigationLink/NavigationLink.tsx) whose functionality is just what I want to achieve. But it seems that it was removed now?

That will helps a lot if we could somehow have it back! :)

**Comment by andrew-levy** [comment]
Yeah it was pretty inefficient and was bloating the library with a bunch of opinionated dependencies, but I plan to bring it back (will take some time tho). In the meantime, you can just use a `HStack` to add the chevron manually. Closing this issue out now! Let me know if you have any more questions.
