### ISSUE TITLE
Use Expo Module API

### ISSUE THREAD

**Issue by andrew-levy** [andrew-levy/swiftui-react-native#26]
Once SwiftUI views are supported in the module api (early 2023 maybe?), I would like to switch some components over to it rather than using javascript implementations. Good candidates include:

- Color
- Image
- Label
- Link
- Shapes

Maybe:
- Slider
- Stepper
- ProgressView

Notice this list doesn't include any container views like Stacks, this is because there currently isn't an easy way to pass children from RN to the SwiftUI view. This will likely come in later iterations of the module api.

Questions:
- ~~Can I have multiple views exported from a single expo module?~~ Answer: Yes https://github.com/expo/expo/tree/ee0de23446792ae6220f8d8f147cdd86a5e02230/packages/expo-maps
- Can I pass default values that need to be @State values in SwiftUI? I think yes, by setting the default value in the init()
- How would RN be notified of a @State value change. Emit an event?

Track PR: https://github.com/expo/expo/pull/19888

**Comment by zpg6** [comment]
Very cool!

**Comment by landonwjohnson** [comment]
does this work with expo and web projects? I have been learning SwiftUI in my free time and I stumbled upon this project, it looks cool!

**Comment by andrew-levy** [comment]
Hey @landonwjohnson thanks! This does work with Expo projects, just not the Expo Go app. You'll need to create a custom dev client since this library relies on a native module (sf symbols). I've never tried to use it in a web app, so I'm not too sure. Maybe you can try and let me know? I'm sure it wouldn't be optimized for web by default, tho.

**Comment by andrew-levy** [comment]
But if you want it to work with the expo go app, i think you can just not install the sf symbol package. I have to check, but im pretty sure the app can handle not having that as a dependency (via dynamic imports)

**Comment by landonwjohnson** [comment]
@andrew-levy if you could get the date picker, and action sheet implemented. That would be wild!! I might use this in my next upcoming project though.

**Comment by andrew-levy** [comment]
Let me know how it goes! I'd be happy to help with any bugs you may find along the way. A few things:

- I actually had a Picker in this library, but removed it because it just wasn't that good. It would need to be a native component, and that's something I want to do in the future. Once expos module api suppers swiftui views, i'll try to add it and other missing views. 
- Actionsheet would be cool, i'll look into it. 
- I have a nice update coming up in the next week or so for List views. I added a Section component to help with some issues someone else was having.
