### ISSUE TITLE
Text wrapping not working properly

### ISSUE THREAD

**Issue by gerzonc** [andrew-levy/swiftui-react-native#37]
Hi again! I've continued testing the library and found that text does not support number of lines, it just has a ellipsis trailing and wrapping doesn't work fine. The video situation is the following: adding string literal's new line doesn't work straight up, it requires to add two new lines.

https://github.com/andrew-levy/swiftui-react-native/assets/36211892/d2ca1aeb-3e47-411e-9c30-85af640d2bfe

**Comment by andrew-levy** [comment]
It looks like this can be achieved with the .fixedSize() modifier as shown [here](https://stackoverflow.com/questions/56558118/multiline-text-view-in-swiftui). You shouldn't have to use the new line chars. I can look into adding this modifier as a prop if that would help. 

Your code would end up looking like:

```tsx
<Text width={width} fixedSize={{ horizontal: false, vertical: true }}> some long text we want to wrap </Text>
```

**Comment by gerzonc** [comment]
> It looks like this can be achieved with the .fixedSize() modifier as shown [here](https://stackoverflow.com/questions/56558118/multiline-text-view-in-swiftui). You shouldn't have to use the new line chars. I can look into adding this modifier as a prop if that would help.
> 
> Your code would end up looking like:
> 
> ```tsx
> <Text width={width} fixedSize={{ horizontal: false, vertical: true }}> some long text we want to wrap </Text>
> ```

Aaah, I see. Didn't know about this modifier before! I do remember doing a similar component previously in SwiftUI, the code went like this:

```swift
HStack {
    Image(systemName: iconName)
        .font(.title)
        .frame(width: 50)
        .padding(.trailing, 10)
    Text(description)
        .fontWeight(.semibold)
    Spacer()
}

```

Great to know we can apply it directly on the Text itself! Thanks!

**Comment by andrew-levy** [comment]
I'm going on vacation for a week but I'll try to add that new modifier before I leave. If not, it may have to wait a week or so.

**Comment by andrew-levy** [comment]
Ok will publish some new modifiers next to help with this, including fixedSize and lineLimit

**Comment by andrew-levy** [comment]
@gerzonc Sorry for the delay. As of swiftui-react-native@6.1.0, you can use the `fixedSize` and `lineLimit` modifiers to try to achieve this!
