### ISSUE TITLE
HeaderScrollContext is not being correctly passed from NavigationViewManager to ScrollView

### ISSUE THREAD

**Issue by andrew-levy** [andrew-levy/swiftui-react-native#4]
## Issue
There is a `HeaderScrollContext` context variable in the `NavigationViewManager` component that eventually gets consumed by the `ScrollView` component to update the amount the user has scrolled (triggering the header animation). When these components are compiled using Rollup, it is not correctly passing the context from `navigation.js` (created here) to `main.js` (consumed here). Instead, `navigation.js` is creating its own context var, and no data is being shared between the two components. 

In `main.js` line 248,

Current:
`const HeaderScrollContext = React.createContext(null);`

I think it should be doing something like this: 
`const HeaderScrollContext = require('./navigation').HeaderScrollContext`
so that we can use the context that was created in the other file.

I also see that `var stack = require('@react-navigation/stack');` is being required in `main.js` and `stack.createStackNavigator();` is being called randomly. Maybe I messed up my import/export somewhere? The only reference to navigation stuff should be the context var.

## Solutions?
I am actively trying to fix this, which has been making me think about how navigation components fit into this project. Ideally, I would like to keep the navigation components (I think?), but I am open to either making them platform agnostic or moving them to a completely different project. Here are some options:

- Do nothing. Leave them in this project with the current setup (which works nicely). Just would need to fix this small issue mentioned above.

- Keep the navigation components, but make them framework agnostic. They would have much less functionality and a lot would be simplified, but we could allow the user to pass in props depending on if they are using react-navigation, react-native-navigation, etc. You could imagine something like this 
`<NavigationLink text='Go to SomeView' action={use whatever navigation function you want here} />`

- Don't change any of the navigation components, but move them to a separate project (something like `swiftui-react-native-navigation`). This could be an optional package that is a wrapper of react-navigation (and maybe more in the future). I definitely want to keep a lot of the animation magic that has been built out in these components already. If you haven't seen some of the animations yet, here is a quick demo:

https://user-images.githubusercontent.com/29075740/109432188-1066c700-79d8-11eb-80d4-80e677edf44d.mov

https://user-images.githubusercontent.com/29075740/109432189-1066c700-79d8-11eb-92cd-ffb5c640bc4c.mov

I'm open to more solutions, but these are the 3 that come to mind. 

@sallar tagging you if you have any ideas! Just wanted to create an issue to keep track of this.

**Comment by sallar** [comment]
hey @andrew-levy! thanks for tagging me here
I'm thinking that react context's should't be created and consumed directly by the package itself. this should be implemented by the end user. so you need to provide a `Provider` component to the user (from the `navigation` package) that the user can then wrap their app around, and then `main.js` package can safely consume it...

**Comment by sallar** [comment]
by the way, `react-navigation` library has this Large Title animation built in... do you need to reimplement this animation?

**Comment by andrew-levy** [comment]
Hey @sallar. Ah that makes more sense now, thanks. I'll go ahead and try that. I wasn't able to find a the Large Title functionality in `react-navigation`, did you mean `react-native-navigation`?

**Comment by sallar** [comment]
@andrew-levy `react-navigation` has another stack navigator called "native" stack navigator, which I really like, and is possible to use with Expo as well:
https://reactnavigation.org/docs/native-stack-navigator/
This one uses the OS's default navigator (on both iOS and Android) and has the large title functionality too. I recommend using this instead of the "javascripty" one

**Comment by andrew-levy** [comment]
@sallar Wow cool I didn't know that existed. Was searching for that for a while but I guess I missed it
