### ISSUE TITLE
Expo-less environment

### ISSUE THREAD

**Issue by liambutler-lawrence** [andrew-levy/swiftui-react-native#45]
What exactly does this library depend on from Expo? We don't use Expo and can't use this library as is.

**Comment by andrew-levy** [comment]
Hey @liambutler-lawrence.  This uses Expo's module api https://docs.expo.dev/modules/module-api/ which makes building native views super easy. Also, expo is now recommended for all new projects. It depends on expo modules core, which should be relatively easy to add even if you aren't fully using expo, but im not too familiar with that.

**Comment by andrew-levy** [comment]
Not sure if you're able to do this easily, but the setup for adding expo modules to a non expo project can be found here https://docs.expo.dev/bare/installing-expo-modules/
