### ISSUE TITLE
Image component doesn't work if expo-image is installed

### ISSUE THREAD

**Issue by Vadko** [andrew-levy/swiftui-react-native#50]
While testing library I've noticed that `Image` component was causing app to crash with `ViewManagerAdapter_Image was not found in the UIManager` error. Initially, I've thought it is related to whole library, but other components were working as expected. After that, I've completely removed `expo-image` package and `Image` from `swiftui-react-native` was working as expected - which means that these two libraries somehow overlap each other.

Expo SDK version: 51.0.31
expo-image version: 1.12.15

**Comment by andrew-levy** [comment]
Hey sorry for the late response @Vadko. It's likely because they have the same name on the native side, which is causing conflicts. Have you figured out a workaround or is it still an issue?

**Comment by samducker** [comment]
I'm experiencing the same issue with expo-image and this library at the current time I haven't found a workaround I will update this if I do.

**Comment by andrew-levy** [comment]
I can see if I can easily update the name of the image component so it doesn't conflict. will keep you posted

**Comment by andrew-levy** [comment]
Published a fix for this in `swiftui-react-native@6.3.1`. Can you please try and let me know if it works? Install the new version, prebuild, and run your app. @Vadko @samducker

**Comment by Vadko** [comment]
many thanks @andrew-levy
