### ISSUE TITLE
onAppear never fires

### ISSUE THREAD

**Issue by acdifran** [andrew-levy/swiftui-react-native#57]
Maybe I am misunderstanding how onAppear works, but I don't see it ever firing. I was trying to use it in list items to fetch more once reaching the bottom, but can't get it to work. I tried a very simple example outside of the List and couldn't get that to fire either. 

```javascript
<RoundedRectangle
  cornerRadius={10}
  frame={{ height: 50, width: 100 }}
  fill="red"
  onAppear={() => {
    console.log('appeared');
  }}
/>
```

**Comment by andrew-levy** [comment]
@acdifran Ahh that's my bad, good catch! Should be fixed in this patch version `swiftui-react-native@6.3.3`

Can you upgrade and let me know if that fixes. I'd recommend doing a clean prebuild after installing.

**Comment by acdifran** [comment]
Working now, thanks for the quick fix!
